### ISSUE TITLE
"go tidy" action uses go1.18, which cannot work with go.mod containing go1.19

### ISSUE THREAD

**Issue by johanneskastl** [dims/community-images#22]
https://github.com/dims/community-images/blob/572f1f579be0a510e026f70b8173abb2cbd44465/.github/workflows/go.yml#L23

```
go: go.mod file indicates go 1.19, but maximum version supported by tidy is 1.18
```

https://github.com/johanneskastl/community-images/actions/runs/4303393509/jobs/7503072657

**Comment by nikhita** [comment]
@johanneskastl can you update the workflow to use:

```yaml
- name: Setup Go
  uses: actions/setup-go@v2
  with:
    go-version: ‘1.19.0’
```
